language: objective-c
osx_image: beta-xcode6.3
before_install:
  - brew update
  - brew uninstall xctool
  - brew install xctool --HEAD
  - xctool -v
  - brew install --devel protobuf
install:
  - scripts/build.sh
  - scripts/makeTests.sh
script:
  - xctool -project ./src/ProtocolBuffers/ProtocolBuffers.xcodeproj -sdk iphonesimulator -scheme ProtocolBuffers build test
  - xctool -project ./src/ProtocolBuffers/ProtocolBuffers.xcodeproj -scheme "ProtocolBuffers(OSX)" build test
