language: objective-c
osx_image: xcode8
before_install:
  - brew update
  - brew install protobuf --devel
install:
  - scripts/build.sh
  - scripts/makeTests.sh
script:
  - xctool -project ./plugin/ProtocolBuffers/ProtocolBuffers.xcodeproj -sdk iphonesimulator -scheme ProtocolBuffers build test
  - xctool -project ./plugin/ProtocolBuffers/ProtocolBuffers.xcodeproj -scheme "ProtocolBuffers(OSX)" build test
